config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  namespace :admin do
    resources :api_clients,     except: %i[show]
    resources :daily_orders,    only:   %i[show]
    resources :meal_categories, except: %i[show]
    resources :menus,           except: %i[destroy]
    resources :users,           only:   %i[index show]

    get 'dates',       to: 'dates#index'
    get 'dates/:date', to: 'dates#show', as: 'date'
  end

  namespace :account do
    resources :daily_orders, only: %i[show new create]
    resource  :profile,      only: %i[edit update]

    get 'dates',       to: 'dates#index'
    get 'dates/:date', to: 'dates#show', as: 'date'

    get 'calendar', to: 'dashboard#calendar'
  end

  namespace :api do
    namespace :v1 do
      resources :daily_orders, only: %i[index]
    end
  end

  root 'account/dates#index'
end

app/models/api_client.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: api_clients
#
#  id           :integer          not null, primary key
#  access_token :string
#  name         :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class ApiClient < ApplicationRecord
  before_create :set_access_token

  scope :ordered,  -> { order(name: :asc) }

  validates :name, presence: true, uniqueness: true

  private

  def set_access_token
    begin
      self.access_token = SecureRandom.hex
    end while self.class.exists?(access_token: access_token)
  end
end

app/controllers/admin/api_clients_controller.rb
# frozen_string_literal: true

module Admin
  class ApiClientsController < BaseController
    def index
      @api_clients = collection.page(params[:page]).per(15)
    end

    def new
      @api_client = collection.new
    end

    def create
      @api_client = collection.new(api_client_params)

      if @api_client.save
        flash[:success] = 'ApiClient was successfully created'
        redirect_to admin_api_clients_path
      else
        render :new
      end
    end

    def edit
      @api_client = resource
    end

    def update
      @api_client = resource

      if @api_client.update(api_client_params)
        flash[:success] = 'ApiClient was successfully updated'
        redirect_to admin_api_clients_path
      else
        render :edit
      end
    end

    def destroy
      @api_client = resource
      @api_client.destroy!

      flash[:success] = 'ApiClient was successfully deleted'

      redirect_to admin_api_clients_path
    end

    private

    def api_client_params
      params.require(:api_client).permit(:name)
    end

    def collection
      ApiClient.ordered
    end

    def resource
      collection.find(params[:id])
    end
  end
end

app/views/admin/api_clients/_form.html.slim
= simple_form_for [:admin, api_client], html: { role: 'form' } do |f|
    = f.input :name
    - unless new_action?
      = f.input :access_token, input_html: { readonly: true }
    = f.submit class: 'btn btn-success'

app/views/admin/api_clients/edit.html.slim
.row
  .col-xs-12
    .panel.panel-default
      .panel-heading Edit API client
      .panel-body
        = render 'admin/api_clients/form', api_client: @api_client

app/views/admin/api_clients/index.html.slim
.row
  .col-xs-12
    .panel.panel-default
      .panel-heading
        | API client
        .pull-right
          = link_to 'Create', new_admin_api_client_path, class: 'btn btn-xs btn-success'
      .panel-body
        table.table.table-striped.table-bordered.table-hover.no-footer
          thead
            tr
              th Name
              th Token
              th Actions

          tbody
            - @api_clients.each do |api_client|
              tr
                td= link_to api_client.name , edit_admin_api_client_path(api_client)

                td= api_client.access_token
                td= link_to 'delete', admin_api_client_path(api_client), method: :delete,
                  data: { confirm: 'Are you sure' }
          tfoot
            tr
              td colspan=3
                .text-center
                  = paginate @api_clients

app/views/admin/api_clients/new.html.slim
.row
  .col-xs-12
    .panel.panel-default
      .panel-heading API client
      .panel-body
        = render 'admin/api_clients/form', api_client: @api_client