config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  namespace :admin do
    resources :api_clients,     except: %i[show]
    resources :daily_orders,    only:   %i[show]
    resources :meal_categories, except: %i[show]
    resources :menus,           except: %i[destroy]
    resources :users,           only:   %i[index show]

    get 'dates',       to: 'dates#index'
    get 'dates/:date', to: 'dates#show', as: 'date'
  end

  namespace :account do
    resources :daily_orders, only: %i[show new create]
    resource  :profile,      only: %i[edit update]

    get 'dates',       to: 'dates#index'
    get 'dates/:date', to: 'dates#show', as: 'date'

    get 'calendar', to: 'dashboard#calendar'
  end

  namespace :api do
    namespace :v1 do
      resources :daily_orders, only: %i[index]
    end
  end

  root 'account/dates#index'
end

app/models/meal_category.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: meal_categories
#
#  id         :integer          not null, primary key
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class MealCategory < ApplicationRecord
  has_many :meals, dependent: :destroy
  has_many :daily_order_meals, dependent: :destroy

  scope :ordered, -> { order(title: :asc) }

  validates :title, presence: true
end

app/controllers/admin/meal_categories_controller.rb
# frozen_string_literal: true

module Admin
  class MealCategoriesController < BaseController
    def index
      @meal_categories = collection.page(params[:page]).per(15)
    end

    def new
      @meal_category = collection.new
    end

    def create
      @meal_category = collection.new(meal_category_params)

      if @meal_category.save
        flash[:success] = 'Category was successfully created'
        redirect_to admin_meal_categories_path
      else
        render :new
      end
    end

    def edit
      @meal_category = resource
    end

    def update
      @meal_category = resource

      if @meal_category.update(meal_category_params)
        flash[:success] = 'Category was successfully updated'
        redirect_to admin_meal_categories_path
      else
        render :edit
      end
    end

    def destroy
      @meal_category = resource
      @meal_category.destroy!

      flash[:success] = 'Category was successfully deleted'

      redirect_to admin_meal_categories_path
    end

    private

    def meal_category_params
      params.require(:meal_category).permit(:title)
    end

    def collection
      MealCategory.ordered
    end

    def resource
      collection.find(params[:id])
    end
  end
end

app/views/admin/meal_categories/_form.html.slim
= simple_form_for [:admin, meal_category], html: { role: 'form' } do |f|
    = f.input :title
    = f.submit class: 'btn btn-success'

app/views/admin/meal_categories/edit.html.slim
.row
  .col-xs-12
    .panel.panel-default
      .panel-heading Edit meal category
      .panel-body
        = render 'admin/meal_categories/form', meal_category: @meal_category

app/views/admin/meal_categories/index.html.slim
.row
  .col-xs-12
    .panel.panel-default
      .panel-heading
        | Meal category
        .pull-right
          = link_to 'Create', new_admin_meal_category_path, class: 'btn btn-xs btn-success'
      .panel-body
        table.table.table-striped.table-bordered.table-hover.no-footer
          thead
            tr
              th Title
              th colspan=2 Actions

          tbody
            - @meal_categories.each do |meal_category|
              tr
                td= meal_category.title
                td= link_to 'edit', edit_admin_meal_category_path(meal_category)
                td= link_to 'delete', admin_meal_category_path(meal_category), method: :delete,
                  data: { confirm: 'Are you sure' }
          tfoot
            tr
              td colspan=3
                .text-center
                  = paginate @meal_categories

app/views/admin/meal_categories/new.html.slim
.row
  .col-xs-12
    .panel.panel-default
      .panel-heading Create meal category
      .panel-body
        = render 'admin/meal_categories/form', meal_category: @meal_category