config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  namespace :admin do
    resources :api_clients,     except: %i[show]
    resources :daily_orders,    only:   %i[show]
    resources :meal_categories, except: %i[show]
    resources :menus,           except: %i[destroy]
    resources :users,           only:   %i[index show]

    get 'dates',       to: 'dates#index'
    get 'dates/:date', to: 'dates#show', as: 'date'
  end

  namespace :account do
    resources :daily_orders, only: %i[show new create]
    resource  :profile,      only: %i[edit update]

    get 'dates',       to: 'dates#index'
    get 'dates/:date', to: 'dates#show', as: 'date'

    get 'calendar', to: 'dashboard#calendar'
  end

  namespace :api do
    namespace :v1 do
      resources :daily_orders, only: %i[index]
    end
  end

  root 'account/dates#index'
end

app/models/menu.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: menus
#
#  id         :integer          not null, primary key
#  date       :date
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Menu < ApplicationRecord
  has_many :meals, inverse_of: :menu, dependent: :destroy
  has_many :daily_orders, dependent: :destroy
  accepts_nested_attributes_for :meals, reject_if: :all_blank, allow_destroy: true

  scope :ordered,  -> { order(date: :asc) }
  scope :in_month, ->(date) { where(date: date.beginning_of_month..date.end_of_month) }

  validates :date, uniqueness: true, presence: true
end

app/controllers/admin/menus_controller.rb
# frozen_string_literal: true

module Admin
  class MenusController < BaseController
    def index
      @menus = collection.in_month(start_date)
    end

    def show
      @menu = resource
    end

    def new
      @menu = Builders::Menu.build_new
    end

    def create
      @menu = Builders::Menu.build_from(resource_params)

      if @menu.save
        redirect_to [:admin, @menu]
      else
        render :new
      end
    end

    def edit
      @menu = resource
    end

    def update
      @menu = resource

      if @menu.update(resource_params)
        redirect_to [:admin, @menu]
      else
        render :edit
      end
    end

    private

    def resource_params
      allowed_params = [
        meals_attributes: %i[id meal_category_id name photo price _destroy]
      ]

      params.require(:menu).permit(allowed_params)
    end

    def collection
      Menu.ordered
    end

    def resource
      collection.find(params[:id])
    end

    def start_date
      Date.parse(params[:start_date])
    rescue ArgumentError, TypeError
      Time.zone.today
    end
  end
end

app/views/admin/menus/_first_course_fields.html.slim
.nested-fields
  = f.input :type, as: :hidden
  .col-xs-3
    = f.input :name
  .col-xs-3
    = f.input :photo
  .col-xs-3
    = f.input :price
  .col-xs-3
    = link_to_remove_association "remove meal", f, class: 'btn btn-danger'
  .clearfix

app/views/admin/menus/_form.html.slim
= simple_form_for [:admin, menu], html: { role: 'form' } do |f|
    h4 Meals
    #meals
      = f.simple_fields_for :meals do |meal|
        = render 'meal_fields', f: meal
      .links
        = link_to_add_association 'Add meal', f, :meals,
          class: 'btn btn-xs btn-warning'
      .clearfix
    hr
    = f.submit class: 'btn btn-success'

app/views/admin/menus/_meal_category_row.html.slim
- if meals.any?
  tr
    td.bg-info colspan=3
      h4= title
  = render partial: 'admin/menus/meals', collection: meals, as: :meal

app/views/admin/menus/_meal_fields.html.slim
.nested-fields
  .col-xs-2
    = f.association :meal_category,
      input_html: { class: 'select2' }
  .col-xs-3
    = f.input :name
  .col-xs-3
    = f.input :photo
  .col-xs-2
    = f.input :price
  .col-xs-2
    = link_to_remove_association "remove meal", f, class: 'btn btn-danger'
  .clearfix

app/views/admin/menus/_meal_type_row.html.slim
- if meals.any?
  tr
    td.bg-info colspan=3
      h6= title
  = render partial: 'admin/menus/meals', collection: meals, as: :meal

app/views/admin/menus/edit.html.slim
.row
  .col-xs-12
    h3 Edit menu on #{l(@menu.date, format: :long)}
.row
  .col-xs-12
    .panel.panel-default
      .panel-heading Create Menu
      .panel-body
        = render 'admin/menus/form', menu: @menu

app/views/admin/menus/index.html.slim
.row
  .col-xs-12
    .panel.panel-default
      .panel-heading
        | Menus
        .pull-right
          = link_to 'Create menu for today', new_admin_menu_path, class: 'btn btn-xs btn-success'

      .panel-body
        = month_calendar attribute: :date, events: @menus do |date, menus|
          = l(date, format: :short)
          br
          - if menus.any?
            - menus.each do |menu|
              = link_to 'Menu', admin_menu_path(menu)
          -elsif Date.current == date
            = link_to 'Create menu', new_admin_menu_path

app/views/admin/menus/new.html.slim
.row
  .col-xs-12
    h3 Create menu on #{l(@menu.date, format: :long)}
.row
  .col-xs-12
    .panel.panel-default
      .panel-heading Create Menu
      .panel-body
        = render 'admin/menus/form', menu: @menu

app/views/admin/menus/show.html.slim
.row
  .col-xs-12
    h3 Menu on #{l(@menu.date, format: :long)}
.row
  .col-xs-12
    .panel.panel-default
      .panel-heading
        | Menu
        .pull-right
          = link_to 'Edit', edit_admin_menu_path(@menu)

      .panel-body
        = render 'shared/meals_per_groups_table',
          grouped_meals: Presenters::Menu.new(@menu).meals_per_categories