config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  namespace :admin do
    resources :api_clients,     except: %i[show]
    resources :daily_orders,    only:   %i[show]
    resources :meal_categories, except: %i[show]
    resources :menus,           except: %i[destroy]
    resources :users,           only:   %i[index show]

    get 'dates',       to: 'dates#index'
    get 'dates/:date', to: 'dates#show', as: 'date'
  end

  namespace :account do
    resources :daily_orders, only: %i[show new create]
    resource  :profile,      only: %i[edit update]

    get 'dates',       to: 'dates#index'
    get 'dates/:date', to: 'dates#show', as: 'date'

    get 'calendar', to: 'dashboard#calendar'
  end

  namespace :api do
    namespace :v1 do
      resources :daily_orders, only: %i[index]
    end
  end

  root 'account/dates#index'
end

app/controllers/account/base_controller.rb
# frozen_string_literal: true

module Account
  class BaseController < ApplicationController
    layout 'account/application'
    before_action :authenticate_user!
  end
end

app/controllers/account/daily_orders_controller.rb
# frozen_string_literal: true

module Account
  class DailyOrdersController < BaseController
    def show
      @daily_order = resource
    end

    def new
      @daily_menu  = Presenters::Menu.new(daily_menu)
      @daily_order = Builders::DailyOrder.new(daily_menu, current_user).build_new
    end

    def create
      @daily_menu  = daily_menu
      @daily_order = Builders::DailyOrder.new(daily_menu, current_user).build_from(resource_params)

      if @daily_order.save
        redirect_to account_daily_order_path(@daily_order)
      else
        render :new
      end
    end

    private

    def resource_params
      params.require(:daily_order).permit(meal_ids: [])
    end

    def collection
      current_user.daily_orders.ordered
    end

    def resource
      collection.find(params[:id])
    end

    def daily_menu
      Menu.find_by!(date: date)
    end

    def date
      params[:date] || Time.zone.today
    end
  end
end

app/controllers/account/dates_controller.rb
# frozen_string_literal: true

module Account
  class DatesController < BaseController
    include DateParser

    def index
      @daily_menu = Menu.find_by(date: Time.zone.today)
    end

    def show
      @date        = date
      @menu        = Menu.find_by(date: @date)
      @daily_order = current_user.daily_orders.find_by(date: @date)
    end
  end
end

app/controllers/account/profiles_controller.rb
# frozen_string_literal: true

module Account
  class ProfilesController < BaseController
    before_action :init_user, only: %i[edit update]

    def edit; end

    def update
      if @user.update(user_params)
        redirect_to edit_account_profile_path
      else
        render :edit
      end
    end

    private

    def init_user
      @user = current_user
    end

    def user_params
      uparams = params.require(:user)

      sanitize_user_password!(uparams)

      uparams.permit(:name, :email, :password, :password_confirmation,
                     :remember_created_at)
    end

    def sanitize_user_password!(uparams)
      return if uparams[:password].present?

      uparams.delete('password')
      uparams.delete('password_confirmation')
    end
  end
end

app/views/layouts/account/_admin_menu.html.slim
  li.nav-item
    = link_to 'API clients', admin_api_clients_path
  li.nav-item
    = link_to 'Meal categoies', admin_meal_categories_path
  li.nav-item
    = link_to 'Menus', admin_menus_path
  li.nav-item
    = link_to 'Users', admin_users_path
  li.nav-item
    = link_to 'User orders', admin_dates_path

app/views/layouts/account/_header.html.slim
.navbar-header
  = link_to 'Meal Delivery', root_path, class: 'navbar-brand'

ul.nav.navbar-top-links.navbar-right
  - if current_user&.admin?
    = render 'layouts/account/admin_menu'
  li.dropdown
    a.dropdown-toggle data-toggle="dropdown" href="#"
      i.fa.fa-user.fa-fw
      i.fa.fa-caret-down
    ul.dropdown-menu.dropdown-user
      li
        = link_to edit_account_profile_path do
          i.fa.fa-user.fa-fw
          | Edit profile
      li.divider
      li
        = link_to destroy_user_session_path, method: :delete do
          i.fa.fa-sign-out.fa-fw
          | Logout
.clearfix

app/views/layouts/account/application.html.slim
doctype html
html
  head
    title Meal Delivery
    = csrf_meta_tags

    = stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .container.root
      .col-xs-offset-1.col-xs-10.page
        .unobtrusive-flash-container
          nav.navbar.navbar-default.navbar-static-top role="navigation" style=("margin-bottom: 0")
            = render 'layouts/account/header'
            .clearfix
            .content-wrapper
              = yield
          = render 'layouts/account/footer'

javascript:
  init_select2()